version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=0.0.9
    image: santiago97/block-view-app:0.0.3
    ports:
      - "5173:5173"
    environment:
      - VITE_API_KEY=${VITE_API_KEY}
    volumes:
      - ./src:/app/src
      - ./public:/app/public
